import { NextRequest, NextResponse } from 'next/server';
import { formatTime, formatTimeSRT } from '@/lib/format-utils';
import type { TranscriptionSegment } from '@/lib/transcriber/types';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { format, segments, fileName } = body as {
      format: string;
      segments: TranscriptionSegment[];
      fileName: string;
    };
    
    if (!segments || !Array.isArray(segments)) {
      return NextResponse.json({ error: 'No segments provided' }, { status: 400 });
    }
    
    switch (format) {
      case 'docx':
        return await exportDocx(segments, fileName);
      case 'pdf':
        return await exportPdf(segments, fileName);
      default:
        return NextResponse.json({ error: 'Unsupported format' }, { status: 400 });
    }
  } catch (err) {
    console.error('Export error:', err);
    return NextResponse.json({
      error: err instanceof Error ? err.message : 'Export failed',
    }, { status: 500 });
  }
}

async function exportDocx(segments: TranscriptionSegment[], fileName: string) {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, BorderStyle } = await import('docx');
  
  const speakerColors: Record<string, string> = {};
  const colorPalette = ['2E7D32', '1565C0', '7B1FA2', 'E65100', 'C62828', '00838F', '4527A0', '00695C'];
  let colorIdx = 0;
  
  for (const seg of segments) {
    if (!speakerColors[seg.speaker]) {
      speakerColors[seg.speaker] = colorPalette[colorIdx % colorPalette.length];
      colorIdx++;
    }
  }
  
  const doc = new Document({
    styles: {
      default: {
        document: {
          run: {
            font: 'Calibri',
            size: 22, // 11pt
          },
        },
      },
    },
    sections: [{
      properties: {
        page: {
          margin: {
            top: 1440, // 1 inch
            right: 1440,
            bottom: 1440,
            left: 1440,
          },
        },
      },
      children: [
        // Title
        new Paragraph({
          text: fileName || 'Transcription',
          heading: HeadingLevel.HEADING_1,
          spacing: { after: 200 },
        }),
        
        // Metadata
        new Paragraph({
          children: [
            new TextRun({
              text: `Generated by autoScriber on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}`,
              italics: true,
              size: 18,
              color: '666666',
            }),
          ],
          spacing: { after: 100 },
        }),
        
        // Speaker legend
        new Paragraph({
          children: [
            new TextRun({
              text: `Speakers: ${Object.keys(speakerColors).join(', ')}`,
              size: 18,
              color: '444444',
            }),
          ],
          spacing: { after: 400 },
        }),
        
        // Horizontal rule
        new Paragraph({
          border: {
            bottom: { style: BorderStyle.SINGLE, size: 6, color: 'CCCCCC' },
          },
          spacing: { after: 200 },
        }),
        
        // Segments
        ...segments.map((seg) => {
          return new Paragraph({
            children: [
              // Timestamp
              new TextRun({
                text: `[${formatTime(seg.startTime)} - ${formatTime(seg.endTime)}]  `,
                size: 18,
                color: '888888',
                font: 'Consolas',
              }),
              // Speaker
              new TextRun({
                text: `${seg.speaker}: `,
                bold: true,
                color: speakerColors[seg.speaker] || '333333',
              }),
              // Text
              new TextRun({
                text: seg.text,
              }),
            ],
            spacing: { after: 120 },
          });
        }),
      ],
    }],
  });
  
  const buffer = await Packer.toBuffer(doc);
  
  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'Content-Disposition': `attachment; filename="${(fileName || 'transcription').replace(/[^a-zA-Z0-9]/g, '_')}.docx"`,
    },
  });
}

async function exportPdf(segments: TranscriptionSegment[], fileName: string) {
  const PDFDocument = (await import('pdfkit')).default;
  
  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 50, left: 60, right: 60 },
    info: {
      Title: fileName || 'Transcription',
      Author: 'autoScriber',
      Subject: 'Bangla Audio Transcription',
    },
  });
  
  const chunks: Buffer[] = [];
  doc.on('data', (chunk: Buffer) => chunks.push(chunk));
  
  const speakerColorsPdf: Record<string, string> = {};
  const colorPalette = ['#2E7D32', '#1565C0', '#7B1FA2', '#E65100', '#C62828', '#00838F', '#4527A0', '#00695C'];
  let colorIdx = 0;
  
  for (const seg of segments) {
    if (!speakerColorsPdf[seg.speaker]) {
      speakerColorsPdf[seg.speaker] = colorPalette[colorIdx % colorPalette.length];
      colorIdx++;
    }
  }
  
  // Title
  doc.fontSize(20).font('Helvetica-Bold').text(fileName || 'Transcription', { align: 'left' });
  doc.moveDown(0.3);
  
  // Metadata
  doc.fontSize(9).font('Helvetica-Oblique').fillColor('#888888')
    .text(`Generated by autoScriber on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}`);
  doc.moveDown(0.2);
  doc.fontSize(9).font('Helvetica').fillColor('#555555')
    .text(`Speakers: ${Object.keys(speakerColorsPdf).join(', ')}`);
  
  // Line
  doc.moveDown(0.5);
  doc.strokeColor('#CCCCCC').lineWidth(0.5)
    .moveTo(60, doc.y)
    .lineTo(doc.page.width - 60, doc.y)
    .stroke();
  doc.moveDown(0.5);
  
  // Segments
  for (const seg of segments) {
    const speakerColor = speakerColorsPdf[seg.speaker] || '#333333';
    const timestamp = `[${formatTime(seg.startTime)} - ${formatTime(seg.endTime)}]`;
    
    // Check if we need a new page
    if (doc.y > doc.page.height - 80) {
      doc.addPage();
    }
    
    // Timestamp
    doc.fontSize(8).font('Courier').fillColor('#999999').text(timestamp, { continued: false });
    
    // Speaker + Text on the same line
    doc.fontSize(10).font('Helvetica-Bold').fillColor(speakerColor)
      .text(`${seg.speaker}: `, { continued: true });
    doc.font('Helvetica').fillColor('#333333')
      .text(seg.text);
    
    doc.moveDown(0.3);
  }
  
  doc.end();
  
  const pdfBuffer = await new Promise<Buffer>((resolve) => {
    doc.on('end', () => {
      resolve(Buffer.concat(chunks));
    });
  });
  
  return new NextResponse(new Uint8Array(pdfBuffer), {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${(fileName || 'transcription').replace(/[^a-zA-Z0-9]/g, '_')}.pdf"`,
    },
  });
}
