'use client';

import { useEffect, useRef, useCallback } from 'react';
import JSZip from 'jszip';
import { useAppStore } from '@/lib/store';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import {
  FileAudio, CheckCircle2, XCircle, Loader2, Download,
  RotateCcw, Archive, Clock, User, AlertTriangle, Ban,
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { formatTime, formatTimeSRT } from '@/lib/format-utils';
import type { TranscriptionSegment, TranscriptionResult } from '@/lib/transcriber/types';
import type { BatchJob } from '@/lib/store';
import styles from './batch-view.module.css';

function buildTxt(segments: TranscriptionSegment[]): string {
  return segments.map(s => `[${formatTime(s.startTime)}] ${s.speaker}: ${s.text}`).join('\n');
}

function buildSrt(segments: TranscriptionSegment[]): string {
  return segments.map((s, i) =>
    `${i + 1}\n${formatTimeSRT(s.startTime)} --> ${formatTimeSRT(s.endTime)}\n${s.speaker}: ${s.text}\n`
  ).join('\n');
}

function buildMd(segments: TranscriptionSegment[], name: string): string {
  const speakers = [...new Set(segments.map(s => s.speaker))];
  let md = `# ${name}\n\n> Generated by autoScriber\n\n## Speakers\n\n`;
  speakers.forEach(sp => { md += `- **${sp}**\n`; });
  md += `\n---\n\n## Transcript\n\n`;
  segments.forEach(s => { md += `**[${formatTime(s.startTime)}]** **${s.speaker}:** ${s.text}\n\n`; });
  return md;
}

function downloadBlob(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
}

export function BatchView() {
  const { batchJobs, setCurrentView, clearBatch, chunkDuration } = useAppStore();
  const processingRef = useRef(false);
  const stopRequestedRef = useRef(false);
  const mountedRef = useRef(true);

  useEffect(() => {
    mountedRef.current = true;
    return () => { mountedRef.current = false; };
  }, []);

  // Transcribe one file via the async job API, polling until it finishes.
  const transcribeOne = useCallback(async (job: BatchJob): Promise<{ result: TranscriptionResult; jobId: string }> => {
    const formData = new FormData();
    formData.append('file', job.file);
    formData.append('model', useAppStore.getState().selectedModel);
    formData.append('chunkDuration', String(useAppStore.getState().chunkDuration));
    formData.append('overlapDuration', String(useAppStore.getState().overlapDuration));

    const res = await fetch('/api/transcribe', { method: 'POST', body: formData });
    const data = await res.json();
    if (!res.ok || !data.jobId) {
      throw new Error(data.error || `Server error (${res.status})`);
    }

    // The job processes in the background; poll it like the single-file flow.
    for (let attempt = 0; attempt < 900; attempt++) {
      if (!mountedRef.current || stopRequestedRef.current) throw new Error('Canceled');
      await new Promise(r => setTimeout(r, 3000));

      const pollRes = await fetch(`/api/jobs?id=${encodeURIComponent(data.jobId)}`);
      if (!pollRes.ok) throw new Error('Failed to check job status');
      const jobData = await pollRes.json();

      if (jobData.status === 'completed') {
        const result: TranscriptionResult = typeof jobData.result === 'string' ? JSON.parse(jobData.result) : jobData.result;
        if (result?.segments?.length > 0) {
          return { result, jobId: data.jobId };
        }
        throw new Error('Transcription finished but produced no segments');
      }
      if (jobData.status === 'failed') {
        throw new Error(jobData.errorMessage || 'Transcription failed');
      }

      // Live progress feedback while polling
      useAppStore.getState().updateBatchJob(job.id, {
        progress: Math.max(jobData.progress ?? 15, 15),
      });
    }

    throw new Error('Transcription timed out after 45 minutes');
  }, []);

  // Process jobs sequentially
  const processQueue = useCallback(async () => {
    if (processingRef.current) return;
    processingRef.current = true;
    stopRequestedRef.current = false;

    const jobs = useAppStore.getState().batchJobs;

    for (const job of jobs) {
      if (!mountedRef.current || stopRequestedRef.current) break;
      if (job.status !== 'queued') continue;

      useAppStore.getState().updateBatchJob(job.id, { status: 'processing', progress: 5 });

      try {
        const { result, jobId } = await transcribeOne(job);
        if (!mountedRef.current) break;
        useAppStore.getState().updateBatchJob(job.id, {
          status: 'done',
          progress: 100,
          segments: result.segments,
          fullText: result.fullText,
          jobId,
          skippedChunks: result.skippedChunks || [],
        });
      } catch (err) {
        if (!mountedRef.current) break;
        const msg = err instanceof Error ? err.message : 'Network error';
        if (msg === 'Canceled') break;
        useAppStore.getState().updateBatchJob(job.id, {
          status: 'failed',
          progress: 0,
          error: msg,
        });
      }
    }

    processingRef.current = false;
  }, [transcribeOne]);

  useEffect(() => {
    if (batchJobs.some(j => j.status === 'queued')) {
      processQueue();
    }
  }, [batchJobs, processQueue]);

  const downloadOne = useCallback((jobId: string, format: 'txt' | 'srt' | 'md') => {
    const job = useAppStore.getState().batchJobs.find(j => j.id === jobId);
    if (!job || !job.segments.length) return;
    const base = job.file.name.replace(/\.[^/.]+$/, '');
    if (format === 'txt') downloadBlob(buildTxt(job.segments), `${base}.txt`);
    else if (format === 'srt') downloadBlob(buildSrt(job.segments), `${base}.srt`);
    else downloadBlob(buildMd(job.segments, base), `${base}.md`);
  }, []);

  const downloadAll = useCallback(async () => {
    const done = useAppStore.getState().batchJobs.filter(j => j.status === 'done');
    if (!done.length) return;
    const zip = new JSZip();
    for (const job of done) {
      const base = job.file.name.replace(/\.[^/.]+$/, '');
      zip.file(`${base}.txt`, buildTxt(job.segments));
      zip.file(`${base}.srt`, buildSrt(job.segments));
      zip.file(`${base}.md`, buildMd(job.segments, base));
    }
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'transcriptions.zip';
    document.body.appendChild(a); a.click();
    document.body.removeChild(a); URL.revokeObjectURL(url);
  }, []);

  const doneCount = batchJobs.filter(j => j.status === 'done').length;
  const failedCount = batchJobs.filter(j => j.status === 'failed').length;
  const totalCount = batchJobs.length;
  const anyActive = batchJobs.some(j => j.status === 'processing' || j.status === 'queued');
  const allFinished = batchJobs.every(j => j.status === 'done' || j.status === 'failed');

  // Stop the whole batch: cancel the in-flight server job (if any) and flag
  // the queue so the polling loop abandons it.
  const stopBatch = useCallback(async () => {
    stopRequestedRef.current = true;
    const state = useAppStore.getState();
    const targets = state.batchJobs.filter(j => j.status === 'processing' || j.status === 'queued');
    const processingJob = targets.find(j => j.status === 'processing');
    if (processingJob?.jobId) {
      try {
        await fetch('/api/jobs', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ id: processingJob.jobId, action: 'cancel' }),
        });
      } catch {}
    }
    targets.forEach(j => state.updateBatchJob(j.id, {
      status: 'failed',
      progress: 0,
      error: 'Cancelled by user',
    }));
  }, []);

  return (
    <div className={styles.root}>
      {/* Header */}
      <div className={styles.header}>
        <div>
          <h2 className={styles.title}>Batch Transcription</h2>
          <p className={styles.subtitle}>
            {doneCount}/{totalCount} completed{failedCount > 0 ? ` · ${failedCount} failed` : ''}
          </p>
        </div>
        <div className={styles.headerActions}>
          {anyActive && (
            <Button variant="destructive" size="sm" onClick={stopBatch} className={styles.btnGap}>
              <Ban className={styles.iconSm} />
              Stop Batch
            </Button>
          )}
          {doneCount > 1 && (
            <Button onClick={downloadAll} className={`${styles.btnGap} ${styles.primaryBtn}`} size="sm">
              <Archive className={styles.iconSm} />
              Download All ZIP
            </Button>
          )}
          {allFinished && (
            <Button variant="outline" size="sm" onClick={() => { clearBatch(); setCurrentView('upload'); }} className={styles.btnGap}>
              <RotateCcw className={styles.iconSm} /> New Batch
            </Button>
          )}
        </div>
      </div>

      {/* Overall progress bar */}
      {!allFinished && (
        <Progress value={Math.round((doneCount + failedCount) / totalCount * 100)} className={styles.overallBar} />
      )}

      {/* Chat-history style job list */}
      <div className={styles.jobList}>
        <AnimatePresence initial={false}>
          {batchJobs.map((job, idx) => {
            const base = job.file.name.replace(/\.[^/.]+$/, '');
            const speakerCount = job.segments.length
              ? new Set(job.segments.map(s => s.speaker)).size
              : 0;

            return (
              <motion.div
                key={job.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.04 }}
              >
                <Card className={`${styles.jobCard} ${
                  job.status === 'done' ? styles.jobCardDone :
                  job.status === 'failed' ? styles.jobCardFailed :
                  job.status === 'processing' ? styles.jobCardProcessing : ''
                }`}>
                  <div className={styles.jobInner}>
                    <div className={styles.jobRow}>
                      {/* Status icon */}
                      <div className={`${styles.statusIconWrap} ${
                        job.status === 'done' ? styles.statusIconDone :
                        job.status === 'failed' ? styles.statusIconFailed :
                        job.status === 'processing' ? styles.statusIconProcessing :
                        styles.statusIconQueued
                      }`}>
                        {job.status === 'done' && <CheckCircle2 className={styles.statusIcon} />}
                        {job.status === 'failed' && <XCircle className={`${styles.statusIcon} ${styles.statusIconDestructive}`} />}
                        {job.status === 'processing' && <Loader2 className={styles.statusIconProcessingIcon} />}
                        {job.status === 'queued' && <FileAudio className={`${styles.statusIcon} ${styles.statusIconMuted}`} />}
                      </div>

                      {/* Info */}
                      <div className={styles.jobBody}>
                        <div className={styles.jobTitleRow}>
                          <p className={styles.jobName}>{job.file.name}</p>
                          <Badge variant="outline" className={styles.jobStatusBadge}>
                            {job.status === 'queued' ? 'Queued' :
                             job.status === 'processing' ? 'Processing...' :
                             job.status === 'done' ? 'Done' : 'Failed'}
                          </Badge>
                        </div>

                        {job.status === 'processing' && (
                          <div className={styles.jobProgressWrap}>
                            <Progress value={job.progress} className={styles.jobProgress} />
                          </div>
                        )}

                        {job.status === 'done' && (
                          <div className={styles.jobMeta}>
                            <span className={styles.metaItem}>
                              <Clock className={styles.iconXs} />
                              {job.segments.length} segments
                            </span>
                            <span className={styles.metaItem}>
                              <User className={styles.iconXs} />
                              {speakerCount} speaker{speakerCount !== 1 ? 's' : ''}
                            </span>
                          </div>
                        )}

                        {job.status === 'failed' && (
                          <p className={styles.jobError}>{job.error}</p>
                        )}

                        {job.status === 'done' && job.skippedChunks.length > 0 && (
                          <p className={styles.skipWarn}>
                            <AlertTriangle className={styles.skipWarnIcon} />
                            {job.skippedChunks.length} chunk{job.skippedChunks.length !== 1 ? 's' : ''} failed (likely quota) — audio at {job.skippedChunks
                              .sort((a, b) => a - b)
                              .map(i => `[${formatTime(i * chunkDuration)} – ${formatTime((i + 1) * chunkDuration)}]`)
                              .join(', ')} may be missing
                          </p>
                        )}

                        {/* Preview snippet */}
                        {job.status === 'done' && job.segments.length > 0 && (
                          <p className={styles.previewSnippet}>
                            &ldquo;{job.segments[0].text}&rdquo;
                          </p>
                        )}
                      </div>

                      {/* Download buttons */}
                      {job.status === 'done' && (
                        <div className={styles.downloadBtns}>
                          {(['txt', 'srt', 'md'] as const).map(fmt => (
                            <Button
                              key={fmt}
                              variant="ghost"
                              size="sm"
                              className={styles.downloadBtn}
                              onClick={() => downloadOne(job.id, fmt)}
                            >
                              <Download className={styles.iconXs} />
                              {fmt.toUpperCase()}
                            </Button>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                </Card>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </div>

      {/* Bottom Download All */}
      {allFinished && doneCount > 1 && (
        <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <Card className={styles.doneBanner}>
            <div className={styles.doneBannerRow}>
              <div>
                <p className={styles.doneTitle}>{doneCount} transcriptions ready</p>
                <p className={styles.doneSub}>Each file includes TXT, SRT, and Markdown</p>
              </div>
              <Button onClick={downloadAll} className={`${styles.btnGap} ${styles.primaryBtn}`}>
                <Archive className={styles.iconMd} />
                Download All as ZIP
              </Button>
            </div>
          </Card>
        </motion.div>
      )}
    </div>
  );
}
