'use client';

import { useEffect, useRef, useCallback } from 'react';
import JSZip from 'jszip';
import { useAppStore } from '@/lib/store';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import {
  FileAudio, CheckCircle2, XCircle, Loader2, Download,
  RotateCcw, Archive, Clock, User,
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { formatTime, formatTimeSRT } from '@/lib/format-utils';
import type { TranscriptionSegment } from '@/lib/transcriber/types';

function buildTxt(segments: TranscriptionSegment[]): string {
  return segments.map(s => `[${formatTime(s.startTime)}] ${s.speaker}: ${s.text}`).join('\n');
}

function buildSrt(segments: TranscriptionSegment[]): string {
  return segments.map((s, i) =>
    `${i + 1}\n${formatTimeSRT(s.startTime)} --> ${formatTimeSRT(s.endTime)}\n${s.speaker}: ${s.text}\n`
  ).join('\n');
}

function buildMd(segments: TranscriptionSegment[], name: string): string {
  const speakers = [...new Set(segments.map(s => s.speaker))];
  let md = `# ${name}\n\n> Generated by autoScriber\n\n## Speakers\n\n`;
  speakers.forEach(sp => { md += `- **${sp}**\n`; });
  md += `\n---\n\n## Transcript\n\n`;
  segments.forEach(s => { md += `**[${formatTime(s.startTime)}]** **${s.speaker}:** ${s.text}\n\n`; });
  return md;
}

function downloadBlob(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click();
  document.body.removeChild(a); URL.revokeObjectURL(url);
}

export function BatchView() {
  const { batchJobs, updateBatchJob, setCurrentView, clearBatch, selectedModel } = useAppStore();
  const processingRef = useRef(false);
  const mountedRef = useRef(true);

  useEffect(() => {
    mountedRef.current = true;
    return () => { mountedRef.current = false; };
  }, []);

  // Process jobs sequentially
  const processQueue = useCallback(async () => {
    if (processingRef.current) return;
    processingRef.current = true;

    const jobs = useAppStore.getState().batchJobs;

    for (const job of jobs) {
      if (!mountedRef.current) break;
      if (job.status !== 'queued') continue;

      updateBatchJob(job.id, { status: 'processing', progress: 5 });

      try {
        const formData = new FormData();
        formData.append('file', job.file);
        formData.append('model', selectedModel);
        formData.append('chunkDuration', String(useAppStore.getState().chunkDuration));
        formData.append('overlapDuration', String(useAppStore.getState().overlapDuration));

        updateBatchJob(job.id, { progress: 15 });

        const res = await fetch('/api/transcribe', { method: 'POST', body: formData });
        const data = await res.json();

        if (!mountedRef.current) break;

        if (res.ok && data.status === 'completed' && data.result?.segments?.length > 0) {
          updateBatchJob(job.id, {
            status: 'done',
            progress: 100,
            segments: data.result.segments,
            fullText: data.result.fullText,
            jobId: data.jobId,
          });
        } else {
          updateBatchJob(job.id, {
            status: 'failed',
            progress: 0,
            error: data.error || 'Transcription failed',
          });
        }
      } catch (err) {
        if (!mountedRef.current) break;
        updateBatchJob(job.id, {
          status: 'failed',
          progress: 0,
          error: err instanceof Error ? err.message : 'Network error',
        });
      }
    }

    processingRef.current = false;
  }, [selectedModel, updateBatchJob]);

  useEffect(() => {
    if (batchJobs.some(j => j.status === 'queued')) {
      processQueue();
    }
  }, [batchJobs, processQueue]);

  const downloadOne = useCallback((jobId: string, format: 'txt' | 'srt' | 'md') => {
    const job = useAppStore.getState().batchJobs.find(j => j.id === jobId);
    if (!job || !job.segments.length) return;
    const base = job.file.name.replace(/\.[^/.]+$/, '');
    if (format === 'txt') downloadBlob(buildTxt(job.segments), `${base}.txt`);
    else if (format === 'srt') downloadBlob(buildSrt(job.segments), `${base}.srt`);
    else downloadBlob(buildMd(job.segments, base), `${base}.md`);
  }, []);

  const downloadAll = useCallback(async () => {
    const done = useAppStore.getState().batchJobs.filter(j => j.status === 'done');
    if (!done.length) return;
    const zip = new JSZip();
    for (const job of done) {
      const base = job.file.name.replace(/\.[^/.]+$/, '');
      zip.file(`${base}.txt`, buildTxt(job.segments));
      zip.file(`${base}.srt`, buildSrt(job.segments));
      zip.file(`${base}.md`, buildMd(job.segments, base));
    }
    const blob = await zip.generateAsync({ type: 'blob' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'transcriptions.zip';
    document.body.appendChild(a); a.click();
    document.body.removeChild(a); URL.revokeObjectURL(url);
  }, []);

  const doneCount = batchJobs.filter(j => j.status === 'done').length;
  const failedCount = batchJobs.filter(j => j.status === 'failed').length;
  const totalCount = batchJobs.length;
  const allFinished = batchJobs.every(j => j.status === 'done' || j.status === 'failed');

  return (
    <div className="max-w-3xl mx-auto space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h2 className="text-xl font-bold tracking-tight">Batch Transcription</h2>
          <p className="text-sm text-muted-foreground mt-0.5">
            {doneCount}/{totalCount} completed{failedCount > 0 ? ` · ${failedCount} failed` : ''}
          </p>
        </div>
        <div className="flex items-center gap-2">
          {doneCount > 1 && (
            <Button onClick={downloadAll} className="gap-1.5 bg-emerald-600 hover:bg-emerald-700" size="sm">
              <Archive className="w-3.5 h-3.5" />
              Download All ZIP
            </Button>
          )}
          {allFinished && (
            <Button variant="outline" size="sm" onClick={() => { clearBatch(); setCurrentView('upload'); }} className="gap-1.5">
              <RotateCcw className="w-3.5 h-3.5" /> New Batch
            </Button>
          )}
        </div>
      </div>

      {/* Overall progress bar */}
      {!allFinished && (
        <Progress value={Math.round((doneCount + failedCount) / totalCount * 100)} className="h-1.5" />
      )}

      {/* Chat-history style job list */}
      <div className="space-y-2">
        <AnimatePresence initial={false}>
          {batchJobs.map((job, idx) => {
            const base = job.file.name.replace(/\.[^/.]+$/, '');
            const speakerCount = job.segments.length
              ? new Set(job.segments.map(s => s.speaker)).size
              : 0;

            return (
              <motion.div
                key={job.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.04 }}
              >
                <Card className={`overflow-hidden transition-colors ${
                  job.status === 'done' ? 'border-emerald-500/30' :
                  job.status === 'failed' ? 'border-destructive/30' :
                  job.status === 'processing' ? 'border-blue-500/30' : ''
                }`}>
                  <div className="p-4">
                    <div className="flex items-start gap-3">
                      {/* Status icon */}
                      <div className={`flex items-center justify-center w-9 h-9 rounded-lg shrink-0 ${
                        job.status === 'done' ? 'bg-emerald-50 dark:bg-emerald-950/30' :
                        job.status === 'failed' ? 'bg-destructive/10' :
                        job.status === 'processing' ? 'bg-blue-50 dark:bg-blue-950/30' :
                        'bg-muted'
                      }`}>
                        {job.status === 'done' && <CheckCircle2 className="w-4.5 h-4.5 text-emerald-600" />}
                        {job.status === 'failed' && <XCircle className="w-4.5 h-4.5 text-destructive" />}
                        {job.status === 'processing' && <Loader2 className="w-4.5 h-4.5 text-blue-500 animate-spin" />}
                        {job.status === 'queued' && <FileAudio className="w-4.5 h-4.5 text-muted-foreground" />}
                      </div>

                      {/* Info */}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <p className="text-sm font-medium truncate">{job.file.name}</p>
                          <Badge variant="outline" className="text-[10px] shrink-0">
                            {job.status === 'queued' ? 'Queued' :
                             job.status === 'processing' ? 'Processing...' :
                             job.status === 'done' ? 'Done' : 'Failed'}
                          </Badge>
                        </div>

                        {job.status === 'processing' && (
                          <div className="mt-2">
                            <Progress value={job.progress} className="h-1" />
                          </div>
                        )}

                        {job.status === 'done' && (
                          <div className="flex items-center gap-3 mt-1 text-xs text-muted-foreground">
                            <span className="flex items-center gap-1">
                              <Clock className="w-3 h-3" />
                              {job.segments.length} segments
                            </span>
                            <span className="flex items-center gap-1">
                              <User className="w-3 h-3" />
                              {speakerCount} speaker{speakerCount !== 1 ? 's' : ''}
                            </span>
                          </div>
                        )}

                        {job.status === 'failed' && (
                          <p className="text-xs text-destructive mt-1 truncate">{job.error}</p>
                        )}

                        {/* Preview snippet */}
                        {job.status === 'done' && job.segments.length > 0 && (
                          <p className="text-xs text-muted-foreground mt-1.5 line-clamp-2 italic">
                            &ldquo;{job.segments[0].text}&rdquo;
                          </p>
                        )}
                      </div>

                      {/* Download buttons */}
                      {job.status === 'done' && (
                        <div className="flex items-center gap-1 shrink-0 flex-wrap justify-end">
                          {(['txt', 'srt', 'md'] as const).map(fmt => (
                            <Button
                              key={fmt}
                              variant="ghost"
                              size="sm"
                              className="h-7 text-[11px] px-2 gap-1"
                              onClick={() => downloadOne(job.id, fmt)}
                            >
                              <Download className="w-3 h-3" />
                              {fmt.toUpperCase()}
                            </Button>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                </Card>
              </motion.div>
            );
          })}
        </AnimatePresence>
      </div>

      {/* Bottom Download All */}
      {allFinished && doneCount > 1 && (
        <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }}>
          <Card className="p-4 border-emerald-500/30 bg-emerald-50/20 dark:bg-emerald-950/10">
            <div className="flex items-center justify-between flex-wrap gap-3">
              <div>
                <p className="text-sm font-medium">{doneCount} transcriptions ready</p>
                <p className="text-xs text-muted-foreground">Each file includes TXT, SRT, and Markdown</p>
              </div>
              <Button onClick={downloadAll} className="gap-1.5 bg-emerald-600 hover:bg-emerald-700">
                <Archive className="w-4 h-4" />
                Download All as ZIP
              </Button>
            </div>
          </Card>
        </motion.div>
      )}
    </div>
  );
}
