import type { TranscriptionSegment } from '@/lib/transcriber/types';
import { formatTime, formatTimeSRT } from '@/lib/format-utils';

export type ExportFormat = 'txt' | 'md' | 'srt' | 'vtt' | 'docx' | 'pdf';

/** Shared time formatting used by every export builder. */
export function formatExportTime(seconds: number): string {
  return formatTime(seconds);
}

export function buildTxt(segments: TranscriptionSegment[]): string {
  return segments
    .map(seg => `[${formatTime(seg.startTime)}] ${seg.speaker}: ${seg.text}`)
    .join('\n');
}

export function buildSrt(segments: TranscriptionSegment[]): string {
  return segments
    .map((seg, idx) => {
      const index = idx + 1;
      const start = formatTimeSRT(seg.startTime);
      const end = formatTimeSRT(seg.endTime);
      return `${index}\n${start} --> ${end}\n${seg.speaker}: ${seg.text}\n`;
    })
    .join('\n');
}

export function buildVtt(segments: TranscriptionSegment[]): string {
  const header = 'WEBVTT\n\n';
  const body = segments
    .map(seg => {
      const start = formatTimeSRT(seg.startTime).replace(',', '.');
      const end = formatTimeSRT(seg.endTime).replace(',', '.');
      return `${start} --> ${end}\n${seg.speaker}: ${seg.text}\n`;
    })
    .join('\n');
  return header + body;
}

export function buildMarkdown(segments: TranscriptionSegment[], title?: string): string {
  const uniqueSpeakers = [...new Set(segments.map(s => s.speaker))];

  let md = title ? `# ${title}\n\n` : '# Transcription\n\n';
  md += `> Generated by **autoScriber** on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}\n\n`;
  md += `## Speakers\n\n`;
  for (const speaker of uniqueSpeakers) {
    md += `- **${speaker}**\n`;
  }
  md += `\n---\n\n## Transcript\n\n`;
  for (const seg of segments) {
    md += `**[${formatTime(seg.startTime)}]** **${seg.speaker}:** ${seg.text}\n\n`;
  }

  return md;
}
